# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
project_name: quality-trace
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  disable: true
before:
  hooks:
    - dir: ./server
      cmd: go mod tidy
    - dir: ./cli
      cmd: go mod tidy
env:
  - VERSION={{ if index .Env "VERSION"  }}{{ .Env.VERSION }}{{ else }}dev{{ end }}
  - QUALITYTRACE_ENV={{ if index .Env "QUALITYTRACE_ENV"  }}{{ .Env.QUALITYTRACE_ENV }}{{ else }}dev{{ end }}
  - ANALYTICS_BE_KEY={{ if index .Env "ANALYTICS_BE_KEY"  }}{{ .Env.ANALYTICS_BE_KEY }}{{ else }}{{ end }}
  - ANALYTICS_FE_KEY={{ if index .Env "ANALYTICS_FE_KEY"  }}{{ .Env.ANALYTICS_FE_KEY }}{{ else }}{{ end }}
builds:
  - id: server
    binary: quality-trace-server
    main: ./server/main.go
    ldflags:
    - -X github.com/kubeshop/quality-trace/server/app.Version={{ .Env.VERSION }}
    - -X github.com/kubeshop/quality-trace/server/app.Env={{ .Env.QUALITYTRACE_ENV }}
    - -X github.com/kubeshop/quality-trace/server/analytics.SecretKey={{ .Env.ANALYTICS_BE_KEY }}
    - -X github.com/kubeshop/quality-trace/server/analytics.FrontendKey={{ .Env.ANALYTICS_FE_KEY }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
    - amd64
  - id: cli
    binary: quality-trace
    main: ./cli/main.go
    ldflags:
    - -X github.com/kubeshop/quality-trace/cli/config.Version={{ .Env.VERSION }}
    - -X github.com/kubeshop/quality-trace/cli/config.Env={{ .Env.QUALITYTRACE_ENV }}
    - -X github.com/kubeshop/quality-trace/cli/analytics.SecretKey={{ .Env.ANALYTICS_BE_KEY }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
    - amd64

dockers:
- image_templates:
  - 'kubeshop/quality-trace:{{ .Env.VERSION }}'
  extra_files:
    - web/build
  build_flag_templates:
  - "--pull"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.name={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.source={{.GitURL}}"
  - "--platform=linux/amd64"
  goos: linux
  goarch: amd64
