apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quality-trace.fullname" . }}
  labels:
    {{- include "quality-trace.labels" . | nindent 4 }}
data:
  config.yaml: |-
    poolingConfig:
      {{- toYaml .Values.poolingConfig | nindent 6 }}
    googleAnalytics:
      enabled: {{.Values.analytics.enabled}}
    postgres:
    {{- if .Values.postgresql.enabled }}
      host: {{ include "quality-trace.postgresql.fullname" . }}
      user: {{.Values.postgresql.auth.username}}
      password: {{.Values.postgresql.auth.password}}
    {{- else }}
      host: {{ .Values.externalPostgresql.host }}
      user: {{ .Values.externalPostgresql.username }}
      password: {{ .Values.externalPostgresql.password }}
    {{- end }}
      port: 5432
      params: sslmode=disable
    telemetry:
      {{- toYaml .Values.telemetry | nindent 6 }}
    server:
      {{- toYaml .Values.server | nindent 6 }}
  provisioning.yaml: |-
    {{- toYaml .Values.provisioning | nindent 4 }}
---
