name: Quality-Trace Docker Image CI - PR

on:
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      GH_URL: https://github.com
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
            fetch-depth: 0
          
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - uses: docker/setup-buildx-action@v1
        name: Set up Docker Buildx

      -
        name: Set up Go environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.1'

      - 
        name: Build
        run: | 
          make dist/quality-trace-server
          make dist/quality-trace
        env:
          GO111MODULE: on

      -
        name: Login to ghcr registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
            
      -
        name: Build and push on PR
        uses: docker/build-push-action@v4
        if: github.event_name == 'pull_request'
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:pr-${{ github.event.pull_request.number }}
          build-args: |
            "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}"
 
